services:
  kafka:
    image: confluentinc/confluent-local:7.5.0
    container_name: kafka_broker
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15-alpine
    container_name: iot_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecreto
      - POSTGRES_DB=sensores
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    container_name: iot_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin